CONFIG_CPP=y

# Enable the standard C++ library
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_NEWLIB_LIBC=y

# Specify C++ standard (Default is C++11)
CONFIG_STD_CPP17=y 
# Options: CONFIG_STD_CPP11, CONFIG_STD_CPP14, CONFIG_STD_CPP17, CONFIG_STD_CPP20

# CONFIG_DK_LIBRARY=y

CONFIG_HWINFO=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y


CONFIG_LOG=y
# CONFIG_LOG_DEFAULT_LEVEL=2
# CONFIG_LOG_DEFAULT_LEVEL=4

