#pico-zephyr-project
#-------------------------------------------------------------------------------
# Zephyr Example Application
#
# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#-------------------------------------------------------------------------------
# NOTE: Please do not remove the #pico-zephyr-project header, it is used by
# the Raspberry Pi Pico VS Code extension to identify the project type.
#-------------------------------------------------------------------------------

cmake_minimum_required(VERSION 3.20.0)

find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(pico-zephyr-app LANGUAGES CXX)

FILE(GLOB app_sources 
    src/main.cpp
    src/AppContext.cpp
    src/thread/*.cpp
    src/peripheral/*.cpp
    # src/util/*.cpp
)
target_sources(app PRIVATE ${app_sources})
# target_sources(app PRIVATE src/main.cpp)
